### ISSUE TITLE
Make admin token optional and create tokens seperately

### ISSUE THREAD

**Issue by elivlo** [boutetnico/ansible-role-influxdb#12]
Hi :)

wdyt of removing the admin_token in `influx setup` here?
https://github.com/boutetnico/ansible-role-influxdb/blob/ccb19603a9cd85b961e368958d4870a21afd10b7/tasks/configure.yml#L18

An then, add the possibility to configure tokens (including the primary admin token) in a separate task like creating users, buckets, etc.?
https://github.com/boutetnico/ansible-role-influxdb/blob/ccb19603a9cd85b961e368958d4870a21afd10b7/tasks/configure.yml#L40-L53

### Why do we need this?
This would allow us to skip the configuration of a default token and make it optional as not everybody needs a primary `admin_token`.

**Comment by elivlo** [comment]
I would change **two** things:

#### Not setting the default token by hand and let it be generated by influxdb:
https://github.com/boutetnico/ansible-role-influxdb/blob/ccb19603a9cd85b961e368958d4870a21afd10b7/tasks/configure.yml#L11-L24

```yaml
- name: Influx setup
  command: influx setup \
    --name default \
    --org {{ influxdb_primary_org }} \
    --bucket {{ influxdb_primary_bucket }} \
    --username {{ influxdb_primary_username }} \
    --password {{ influxdb_primary_password }} \
    --force
  register: _setup
  failed_when:
    - _setup.rc != 0
    - '"has already been set up" not in _setup.stderr'
  changed_when: _setup.rc == 0
  become: true
```

#### And add a new task that creates `all-access` tokens for users that should have an administrative role for their organization:
```yaml
- name: Ensure admin keys exists for org admin users
  command: influx auth create \
    --user "{{ item.name }}" \
    --description "{{ item.name }} admin token for {{ item.org }}" \
    --org "{{ item.org }}" \
    --all-access
  loop: "{{ influxdb_users }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.org_admin | default(False) | bool
  register: _admin_token
  failed_when:
    - _admin_token.rc != 0
    - '"already exists" not in _admin_token.stderr'
  changed_when: _admin_token.rc == 0
  become: true
```

@boutetnico What do you think of this proposal? :)
